version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "cluster.name=es-cluster"
      - "discovery.zen.minimum_master_nodes=1"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "node.master=true"
      - "node.data=true"
      - "node.ingest=true"
      - "node.name=es-node.{{.Task.Slot}}.{{.Node.Hostname}}"
      - "LOGSPOUT=ignore"
    networks:
       - private
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  fluentd-elasticsearch:
    image: ruanbekker/fluentd-elasticsearch
    environment:
      FLUENTD_CONF: 'fluent.conf'
      FLUENTD_HOSTNAME: '{{.Node.Hostname}}'
    ports:
      - 24224:24224
      - 24224:24224/udp
    user: root
    configs:
      - source: fluent-elasticsearch-conf.v1
        target: /fluentd/etc/fluent.conf
    networks:
      - private
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:${ELASTIC_VERSION:-6.7.0}
    networks:
      - private
    ports:
      - target: 5601
        published: 5601
        protocol: tcp
        mode: host
    environment:
      - SERVER_NAME=kibana.${DOMAIN:-localhost}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_HOST:-http://elasticsearch}:${ELASTICSEARCH_PORT:-9200}
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOST:-http://elasticsearch}:${ELASTICSEARCH_PORT:-9200}
    deploy:
      mode: replicated
      replicas: 1

networks:
  private:
    external: true

configs:
  fluent-elasticsearch-conf.v1:
    file: ./fluentd/fluentd.conf
